package com.huyuans.bailian.controller;

import com.huyuans.bailian.model.request.ChatRequest;
import com.huyuans.bailian.model.response.ChatResponse;
import com.huyuans.bailian.model.response.ChatStreamResponse;
import com.huyuans.bailian.service.BailianService;
import com.huyuans.bailian.util.StreamUtils;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.Collections;

@Slf4j
@RestController
@RequestMapping("/api/v1/chat")
@RequiredArgsConstructor
public class ChatController {

    private final BailianService bailianService;

    @PostMapping
    public Mono<ResponseEntity<ChatResponse>> chat(@RequestBody ChatRequest request) {
        log.info("Received chat request, model: {}", request.getModel());
        return bailianService.chat(request)
                .map(ResponseEntity::ok)
                .doOnError(e -> log.error("Chat request failed: {}", e.getMessage()))
                .onErrorResume(e -> {
                    ChatResponse errorResponse = ChatResponse.builder()
                            .error(Collections.singletonMap("error", e.getMessage()))
                            .build();
                    return Mono.just(ResponseEntity.internalServerError().body(errorResponse));
                });
    }

    @PostMapping(value = "/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<ChatStreamResponse> chatStream(@RequestBody ChatRequest request) {
        log.info("Received stream chat request, model: {}", request.getModel());
        return bailianService.chatStreamFlux(request)
                .doOnError(e -> log.error("Stream chat request failed: {}", e.getMessage()))
                .onErrorResume(e -> {
                    ChatStreamResponse errorResponse = ChatStreamResponse.builder()
                            .id("error")
                            .build();
                    return Flux.just(errorResponse);
                });
    }

    @PostMapping("/async")
    public Mono<ResponseEntity<AsyncChatResponse>> chatAsync(@RequestBody ChatRequest request) {
        log.info("Received async chat request, model: {}", request.getModel());
        return bailianService.chat(request)
                .map(response -> {
                    String content = "";
                    if (response.getChoices() != null && !response.getChoices().isEmpty()) {
                        content = response.getChoices().get(0).getMessage().getContent();
                    }
                    return ResponseEntity.ok(new AsyncChatResponse(
                            response.getId(),
                            response.getModel(),
                            content,
                            response.getUsage() != null ? response.getUsage().getTotalTokens() : 0
                    ));
                })
                .doOnError(e -> log.error("Async chat request failed: {}", e.getMessage()))
                .onErrorResume(e -> {
                    AsyncChatResponse errorResponse = new AsyncChatResponse(
                            null,
                            request.getModel(),
                            "Error: " + e.getMessage(),
                            0
                    );
                    return Mono.just(ResponseEntity.internalServerError().body(errorResponse));
                });
    }

    @lombok.Data
    @lombok.AllArgsConstructor
    @lombok.NoArgsConstructor
    public static class AsyncChatResponse {
        private String id;
        private String model;
        private String content;
        private int totalTokens;
    }
}

// Generated by Claude Code