package com.huyuans.bailian.controller;

import com.huyuans.bailian.config.BailianProperties;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;
import reactor.core.publisher.Mono;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.Map;

@Slf4j
@RestController
@RequestMapping("/api/v1/health")
@RequiredArgsConstructor
public class HealthController {

    private final BailianProperties properties;

    private static final String HEALTH_CHECK_PATH = "/api/v1/models";
    private static final long HEALTH_CHECK_TIMEOUT_MS = 5000;

    @GetMapping
    public Mono<ResponseEntity<HealthResponse>> health() {
        log.debug("Health check requested");
        HealthResponse response = new HealthResponse(
                "UP",
                "bailian-spring-boot-starter",
                LocalDateTime.now(),
                Map.of(
                        "baseUrl", properties.getBaseUrl(),
                        "defaultModel", properties.getDefaultModel()
                )
        );
        return Mono.just(ResponseEntity.ok(response));
    }

    @GetMapping("/bailian")
    public Mono<ResponseEntity<BailianHealthResponse>> bailianHealth() {
        log.info("Checking Bailian API connectivity");
        WebClient webClient = WebClient.builder()
                .baseUrl(properties.getBaseUrl())
                .defaultHeader("Authorization", "Bearer " + properties.getApiKey())
                .build();

        return webClient.get()
                .uri(HEALTH_CHECK_PATH)
                .retrieve()
                .bodyToMono(String.class)
                .timeout(Duration.ofMillis(HEALTH_CHECK_TIMEOUT_MS))
                .map(response -> {
                    log.info("Bailian API health check succeeded");
                    return ResponseEntity.ok(new BailianHealthResponse(
                            "UP",
                            "Bailian API connection successful",
                            properties.getBaseUrl(),
                            properties.getDefaultModel(),
                            LocalDateTime.now()
                    ));
                })
                .onErrorResume(WebClientResponseException.class, e -> {
                    log.warn("Bailian API health check failed: HTTP {}", e.getStatusCode());
                    return Mono.just(ResponseEntity.status(e.getStatusCode())
                            .body(new BailianHealthResponse(
                                    "DOWN",
                                    "HTTP " + e.getStatusCode() + ": " + e.getStatusText(),
                                    properties.getBaseUrl(),
                                    properties.getDefaultModel(),
                                    LocalDateTime.now()
                            )));
                })
                .onErrorResume(Exception.class, e -> {
                    log.warn("Bailian API health check failed: {}", e.getMessage());
                    return Mono.just(ResponseEntity.internalServerError()
                            .body(new BailianHealthResponse(
                                    "DOWN",
                                    "Connection failed: " + e.getMessage(),
                                    properties.getBaseUrl(),
                                    properties.getDefaultModel(),
                                    LocalDateTime.now()
                            )));
                });
    }

    @lombok.Data
    @lombok.AllArgsConstructor
    @lombok.NoArgsConstructor
    public static class HealthResponse {
        private String status;
        private String service;
        private LocalDateTime timestamp;
        private Map<String, Object> details;
    }

    @lombok.Data
    @lombok.AllArgsConstructor
    @lombok.NoArgsConstructor
    public static class BailianHealthResponse {
        private String status;
        private String message;
        private String baseUrl;
        private String defaultModel;
        private LocalDateTime timestamp;
    }
}

// Generated by Claude Code