package com.huyuans.bailian.controller;

import com.huyuans.bailian.config.BailianProperties;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import reactor.core.publisher.Mono;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Slf4j
@RestController
@RequestMapping("/api/v1/models")
@RequiredArgsConstructor
public class ModelController {

    private final BailianProperties properties;

    private static final List<ModelInfo> AVAILABLE_MODELS = Arrays.asList(
            new ModelInfo("qwen-turbo", "通义千问Turbo", "快速响应的通用大语言模型", 8192),
            new ModelInfo("qwen-plus", "通义千问Plus", "均衡性能的通用大语言模型", 32768),
            new ModelInfo("qwen-max", "通义千问Max", "最强性能的通用大语言模型", 8192),
            new ModelInfo("qwen-long", "通义千问Long", "长文本处理模型", 10000),
            new ModelInfo("text-embedding-v3", "文本嵌入V3", "文本向量嵌入模型", 8192)
    );

    @GetMapping
    public Mono<ResponseEntity<ModelsResponse>> getModels() {
        log.info("Getting available models list");
        ModelsResponse response = new ModelsResponse(
                "list",
                AVAILABLE_MODELS,
                properties.getDefaultModel()
        );
        return Mono.just(ResponseEntity.ok(response));
    }

    @GetMapping("/{modelId}")
    public Mono<ResponseEntity<ModelInfo>> getModel(@PathVariable String modelId) {
        log.info("Getting model details for: {}", modelId);
        return Mono.justOrEmpty(
                AVAILABLE_MODELS.stream()
                        .filter(m -> m.getId().equals(modelId))
                        .findFirst()
                        .map(ResponseEntity::ok)
        ).switchIfEmpty(Mono.just(ResponseEntity.notFound().build()));
    }

    @lombok.Data
    @lombok.AllArgsConstructor
    @lombok.NoArgsConstructor
    public static class ModelInfo {
        private String id;
        private String name;
        private String description;
        private int maxContextLength;
        private boolean isDefault;

        public ModelInfo(String id, String name, String description, int maxContextLength) {
            this.id = id;
            this.name = name;
            this.description = description;
            this.maxContextLength = maxContextLength;
            this.isDefault = id.equals("qwen-turbo");
        }
    }

    @lombok.Data
    @lombok.AllArgsConstructor
    @lombok.NoArgsConstructor
    public static class ModelsResponse {
        private String object;
        private List<ModelInfo> data;
        private String defaultModel;
    }
}

// Generated by Claude Code